pipeline {
  agent any

  stages {

    stage('Terraform') {
      steps {
        sh '''
        cd terraform
        terraform init
        terraform apply -auto-approve
        '''
      }
    }

    stage('Ansible') {
      steps {
        sh '''
        ssh ec2-user@<ansible-ip> "
        cd ansible &&
        ansible-playbook -i inventory.ini playbook.yml
        "
        '''
      }
    }
  }
}
