plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  instance-state-name: running

hostnames:
  - instance-id

compose:
  ansible_host: instance-id

keyed_groups:
  - key: ec2_tags.Name
    prefix: tag_Name_

  - key: ec2_tags.Role
    prefix: tag_Role_