- hosts: all
  serial: 1
  gather_facts: no
  tasks:
    - name: Test ping
      ping:

- hosts: all
  become: yes
  roles:
    - common

- hosts: jenkins
  become: yes
  roles:
    - jenkins

- hosts: apache
  become: yes
  roles:
    - apache

- hosts: mysql
  become: yes
  roles:
    - mysql

- hosts: monitoring
  become: yes
  roles:
    - prometheus
    - grafana